name: Python application - MyPy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    name: Python ${{ matrix.python-version }} sample

    steps:
    - uses: actions/checkout@v4

    - name: Install poetry
      run: pipx install poetry

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python-version}}
        cache: 'poetry'

    - name: Instal
      run: |
        poetry install

    - name: Test with MyPy
      run: |
        poetry run mypy .
