name: Python application - API Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    name: Python ${{ matrix.python-version }} sample

    steps:
    - uses: actions/checkout@v4

    - name: Install poetry
      run: pipx install poetry

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python-version}}
        cache: 'poetry'

    - name: Clone Redis
      uses: actions/checkout@v4
      with:
        repository: redis/redis
        path: redis-tmp
        ref: 7.2

    - name: Install and setup redis
      run: |
        mv redis-tmp ../redis
        pushd ..
        pushd redis
        make
        popd
        popd

    - name: Install with poetry
      run: |
        poetry install
        echo PHISHTANK_HOME=`pwd` > .env
        poetry run start

    - name: Clone PyPhishtankLookup
      uses: actions/checkout@v4
      with:
        repository: Lookyloo/PyPhishtankLookup
        path: PyPhishtankLookup

    - name: Run API tests
      run: |
        pushd PyPhishtankLookup
        poetry install
        poetry run pytest tests/test_web.py
        popd

    - name: Stop instance
      run: |
        poetry run stop

    - name: Test update script
      run: |
        poetry run update --yes
        sleep 30
        poetry run stop
